name: CI

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: ~

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  install:
    runs-on: ubuntu-latest
    name: Install
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install
        run: bun install --frozen-lockfile